<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'ZfmFoundation\Module'                        => __DIR__ . '/Module.php',
    'ZfmFoundation\View\Helper\Alert'                => __DIR__ . '/src/ZfmFoundation/View/Helper/Alert.php',
    'ZfmFoundation\View\Helper\Label'                => __DIR__ . '/src/ZfmFoundation/View/Helper/Label.php',
    'ZfmFoundation\View\Helper\Tooltip'                => __DIR__ . '/src/ZfmFoundation/View/Helper/Tooltip.php',
    'ZfmFoundation\View\Helper\Badge'                => __DIR__ . '/src/ZfmFoundation/View/Helper/Badge.php',
    'ZfmFoundation\View\Helper\Panel'                => __DIR__ . '/src/ZfmFoundation/View/Helper/Panel.php',
);